## Documentation: http://docs.travis-ci.com/user/languages/julia/

notifications:
  email: false

os:
  - osx

before_script:
  - brew update-reset
  - if [[ "$TRAVIS_OS_NAME" == osx   ]]; then brew install mysql@5.7    ; fi
