## Documentation: http://docs.travis-ci.com/user/languages/julia/

notifications:
  email: false

os:
  - osx

services:
  - mysql

before_script:
  - if [[ "$TRAVIS_OS_NAME" == osx   ]]; then brew install mysql@5.7    ; fi
